config/routes.rb
Rails.application.routes.draw do
  
  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :user_friendships do
    member do
      put :accept
    end
  end

  resources :statuses
    get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get '/:profilename', to: 'profiles#show', as: 'profile'

end

app/models/document.rb
class Document < ActiveRecord::Base
	has_attached_file :attachment
	validates_attachment_content_type :attachment, :content_type => /\Aimage/
	validates_attachment_file_name :attachment, :matches => [/png\Z/, /jpe?g\Z/]

  belongs_to :status
end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :user
	has_one :document

	accepts_nested_attributes_for :document

	validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :statuses
  has_many :user_friendships

  #this shit is crazy
  has_many :friends, -> { where user_friendships: { state: 'accepted'} }, through: :user_friendships  
  has_many :pending_user_friendships, -> {where state: 'pending'}, class_name: 'UserFriendship', foreign_key: :user_id
  has_many :pending_friends, through: :pending_user_friendships, source: :friend

  def full_name
  	first_name + " " + last_name
  end

  #def to_param
    #profile_name
  #end

  def gravatar_url
  	stripped_email = email.strip
  	downcased_email = stripped_email.downcase
  	hash = Digest::MD5.hexdigest(downcased_email)

  	"http://www.gravatar.com/#{hash}" 
  end
  
  
end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'

	after_destroy :delete_mutual_friendship!

	state_machine :state, initial: :pending do 

		after_transition on: :accept, do: [:send_acceptance_email, :accept_mutual_friendship!]

		state :requested 

		event :accept do 
			transition any => :accepted
		end

	end

	def self.request(user1, user2)
		transaction do
			friendship1 = create(user: user1, friend: user2, state: 'pending')
			friendship2 = create(user: user2, friend: user1, state: 'requested')

			friendship1.send_request_email
			friendship1
		end
	end

	def send_request_email
		UserNotifier.friend_requested(id).deliver
	end

	def send_acceptance_email
		UserNotifier.friend_request_accepted(id).deliver
	end

	def mutual_friendship
		self.class.where({user_id: friend_id, friend_id: user_id}).first
	end


	def accept_mutual_friendship!
		# Grab the mutual friendship and update the state without using the
		# state machine. This prevents us from invoking callbacks
		mutual_friendship.update_attribute(:state, 'accepted')
	end

	def delete_mutual_friendship
		mutual_friendship.delete
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	
  	@user = User.find_by_profile_name(params[:profilename])
  	
  	if @user
  		@statuses = @user.statuses.all
  		render action: :show
  	else
  		render file: 'public/404', status: 404, formats: [:html]
  end
end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
  private
 
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :profile_name, :email, :password, :password_confirmation)
  end
 
  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create] 
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = current_user.statuses.new
    @status.build_document
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = current_user.statuses.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:user_id, :content,
                                     document_attributes: [:id, :attachment])
    end
end

app/controllers/user_friendships_controller.rb
class UserFriendshipsController < ApplicationController
  #before_filter :authenticate_user!

  def index
    @user_friendships = current_user.user_friendships.all
  end

  def accept
    @user_friendship = current_user.user_friendships.find(params[:id])
    if @user_friendship.accept!
      flash[:success] = "You are now friends with #{@user_friendship.friend.first_name}"
    else
      flash[:error] = "That friendship could not be accepted"
    end
      redirect_to user_friendships_path
  end

  def edit
    @user_friendship = current_user.user_friendships.find(params[:id])
  end

  def destroy
    @user_friendship = current_user.user_friendships.find(params[:id])
    @user_friendship.delete
    redirect_to root_path
  end

  def new
    #@friend = User.last
    #@user_friendship = current_user.user_friendships.new(friend: @friend)
  	if params[:friend_id]
  		@friend = User.find(params[:friend_id])
      #@friend = User.where(profile_name: params[:user_friendship][:friend_id]).first
  		#@user_friendship = current_user.user_friendships.new(friend: @friend)
      @user_friendship = UserFriendship.request(current_user, @friend)

      if @user_friendship.new_record?
        flash[:error] = "There was a problem with your request"
      else
        flash[:success] = "Friend request sent"
      end
        redirect_to profile_path(@friend.profile_name)

  	else
  		flash[:error] = "Friend required"
      redirect_to root_path
	end 

	rescue ActiveRecord::RecordNotFound
		render file: 'public/404', status: :not_found
	end

  def create
    if params[:user_friendship] && params[:user_friendship].has_key?(:friend_id)
      @friend = User.where(profile_name: params[:user_friendship][:friend_id]).first
      #@friend = User.find(params[:friend_id])
      #@user_friendship = current_user.user_friendships.new(friend: @friend)
      @user_friendship = UserFriendship.request(current_user, @friend)
      if @user_friendship.new_record?
        flash[:error] = "There was a problem with your request"
       else
        flash[:success] = "Friend request sent"
      end
        redirect_to profile_path(@friend.profile_name)

    else
      flash[:error] = "Friend required"
      redirect_to root_path
    end 
  end
	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(type)
		case type
		when :alert
			"alert-error"
		when :notice
			"alert-success"
		else 
			""
	end
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" >
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Treebook</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "All Statuses", statuses_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to 'Friends', user_friendships_path %></li>
            <li><%= link_to current_user.full_name, edit_user_registration_path %></li>
            <li><%= link_to "Logout", logout_path %></li>
        <% else %>
            <li><%= link_to "Registration", register_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>

  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
<h1><%= @user.full_name %></h1>
<% if @statuses %>
<% @statuses.each do |status| %>
	<div class="well">
		<%= status.content %>
		<br>
		<%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
		</div>
<% end %>
<% end %>
</div>

app/views/statuses/_form.html.erb
<%= simple_form_for @status, html: {multipart: true} do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.input :content %>

  <%= f.fields_for :document do |document_fields| %>
    <%= document_fields.input :attachment, as: :file %>
  <% end %>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<br><br><br><br>

<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<br><br><br><br>
<div class="page-header">
  <h1>All Statuses</h1>
  <%= link_to "Add Friend", new_user_friendship_path(friend_id: @user), class: 'btn primary' %>
  <%= link_to "Post a New Status", new_status_path, class: "btn btn-success" %>
</div>



<% @statuses.each do |status| %>
<div class="status">
  <div class="row">
    <div class="span1">
      <%= image_tag status.user.gravatar_url %>
    </div>
    <div class="span7">
    <p><%= status.user.first_name %></p>
    <%= link_to "Add Friend", new_user_friendship_path(friend_id: status.user.id), class: 'btn primary' %>
    <p><%= status.content %></p>
    <% if status.document && status.document.attachment? %>
      <p>
        This is an example
        <%= link_to status.document.attachment_file_name, status.document.attachment.url %>
      </p>
    <% end %>
    <div class="meta">
      <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
      <span class="admin">
        | <%= link_to "Edit", edit_status_path(status) %>
        <%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure you want to delete this status?" } %> 
      </span>
    </div> <!--end meta -->
  </div> <!--end span 7 -->
</div> <!--end row -->
</div> <!--end status -->

  <% end %>

app/views/statuses/new.html.erb
<br><br><br><br>

<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<br><br><br><br>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
 
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>


<% if @status.document && @status.document.attachment? %>
<p>
	This is an example
	<%= link_to @status.document.attachment_file_name, @status.document.attachment.url %>
</p>
<% end %>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>

app/views/user_friendships/edit.html.erb
<h1>Editing current friendship</h1>

<% if @user_friendship.requested? %>
	<h3>Do you really want to be friends with <%= @friend.first_name %></h3>
<% end %>

<div class="form-actions">
	<% if @user_friendship.requested? %>
		<% form_for @user_friendship, url: accept_user_friendship_path(@user_friendship), method: :put do |form| %>
		<%= submit_tag "Accept Friendship", class: 'btn btn-primary' %>
		<% end %>
	<% end %>
</div>

app/views/user_friendships/index.html.erb
<h1>Here are all of your friends</h1>

<% @user_friendships.each do |friendship| %>
	<!-- How do we know that the friendship has a .friend method? -->
	<% friend = friendship.friend %>

	<div id = "<%= dom_id(friendship) %>" class="friend row">
		<div class="span1">
			<%= link_to image_tag(friend.gravatar_url), profile_path(friend) %>
		</div>

		<div class="span7">
			<strong><%= friend.full_name %></strong>
			<br />
			
			<% if friendship.pending? %>
				<em>Friendship is pending</em>
				<%= link_to 'Cancel Request', user_friendship_path(friendship), :method => :delete %>
				<%= link_to "Accept friendship", accept_user_friendship_path(friendship), method: :put %>.
			<% end %>

			<% if friendship.requested? %>
				<em>Friendship requested</em>
				<%= link_to "Accept friendship", accept_user_friendship_path(friendship), method: :put %>.
				<%= link_to 'Reject', user_friendship_path(friendship), :method => :delete %>
			<% end %>

			<% if friendship.accepted? %>
				<em>You are friends</em>
				<%= link_to "Update friendship", edit_user_friendship_path(friendship) %>.
			<% end %>

		</div>
	</div>
<% end %>

app/views/user_friendships/new.html.erb
<% if @friend %>
	<h1><%= @friend.full_name %></h1>


	<%= form_for @user_friendship, method: :post do |form| %>
	    <div class="form form-actions">
	    	<br>
	     <%= submit_tag "Yes, Add Friend", class: 'btn btn-primary' %>
	     <br>
	  	 <%= form.hidden_field :friend_id, value: @friend.profile_name %>
	  	 
	  	 <%= link_to "Cancel", profile_path(@friend.profile_name), class: 'btn' %>
	  	</div>

  	<% end %>
<% end %>

app/views/user_notifier/friend_request_accepted.html.erb
<h1>You have a friend request </h1>

app/views/user_notifier/friend_requested.html.erb
<h1>You have a friend request </h1>